server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/furniture_catalogue
    username: borovyk
    password: password
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQL95Dialect
